#ifndef LED_H_
#define LED_H_

#define LED0_PORTSET GPIOC_PSOR
#define LED1_PORTSET GPIOC_PSOR
#define LED2_PORTSET GPIOD_PSOR
#define LED3_PORTSET GPIOC_PSOR
#define LED4_PORTSET GPIOC_PSOR
#define LED5_PORTSET GPIOC_PSOR

#define LED0_PORTCLEAR GPIOC_PCOR
#define LED1_PORTCLEAR GPIOC_PCOR
#define LED2_PORTCLEAR GPIOD_PCOR
#define LED3_PORTCLEAR GPIOC_PCOR
#define LED4_PORTCLEAR GPIOC_PCOR
#define LED5_PORTCLEAR GPIOC_PCOR

#define LED0_PORTTOGGLE GPIOC_PTOR
#define LED1_PORTTOGGLE GPIOC_PTOR
#define LED2_PORTTOGGLE GPIOD_PTOR
#define LED3_PORTTOGGLE GPIOC_PTOR
#define LED4_PORTTOGGLE GPIOC_PTOR
#define LED5_PORTTOGGLE GPIOC_PTOR

#define LED0_PORTMASK (1<<5)
#define LED1_PORTMASK (1<<0)
#define LED2_PORTMASK (1<<1)
#define LED3_PORTMASK (1<<3)
#define LED4_PORTMASK (1<<4)
#define LED5_PORTMASK (1<<7)

void InitLeds();
inline void LedOn(int pin);
inline void LedOff(int pin);
inline void LedToggle(int pin);

#endif  // LED_H_